version: "3"
services:
 web:
   build: .
   volumes:
    - .:/web
    - node_modules:/api/node_modules
   ports:
    - "8030:8030"
    - "9002:9002"
   environment:
    - SERVER_HOST_NAME=http://127.0.0.1
   networks:
    - healthmap-net
volumes:
 node_modules:
networks:
 healthmap-net:
   driver: bridge